//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DAL.WebReference_staff {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StaffManagementV2Soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicEmploymentInfo))]
    public partial class StaffManagementV2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStaffIDByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmploymentInfoByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmploymentInfoByUserIDAndValidDateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StaffManagementV2() {
            this.Url = global::DAL.Properties.Settings.Default.DAL_WebReference_staff_StaffManagementV2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStaffIDByUserIDCompletedEventHandler GetStaffIDByUserIDCompleted;
        
        /// <remarks/>
        public event GetEmploymentInfoByUserIDCompletedEventHandler GetEmploymentInfoByUserIDCompleted;
        
        /// <remarks/>
        public event GetEmploymentInfoByUserIDAndValidDateCompletedEventHandler GetEmploymentInfoByUserIDAndValidDateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStaffIDByUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BasicStaffInfo[] GetStaffIDByUserID(int UserID) {
            object[] results = this.Invoke("GetStaffIDByUserID", new object[] {
                        UserID});
            return ((BasicStaffInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStaffIDByUserIDAsync(int UserID) {
            this.GetStaffIDByUserIDAsync(UserID, null);
        }
        
        /// <remarks/>
        public void GetStaffIDByUserIDAsync(int UserID, object userState) {
            if ((this.GetStaffIDByUserIDOperationCompleted == null)) {
                this.GetStaffIDByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStaffIDByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetStaffIDByUserID", new object[] {
                        UserID}, this.GetStaffIDByUserIDOperationCompleted, userState);
        }
        
        private void OnGetStaffIDByUserIDOperationCompleted(object arg) {
            if ((this.GetStaffIDByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStaffIDByUserIDCompleted(this, new GetStaffIDByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmploymentInfoByUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmploymentInfo[] GetEmploymentInfoByUserID(int piUserID) {
            object[] results = this.Invoke("GetEmploymentInfoByUserID", new object[] {
                        piUserID});
            return ((EmploymentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmploymentInfoByUserIDAsync(int piUserID) {
            this.GetEmploymentInfoByUserIDAsync(piUserID, null);
        }
        
        /// <remarks/>
        public void GetEmploymentInfoByUserIDAsync(int piUserID, object userState) {
            if ((this.GetEmploymentInfoByUserIDOperationCompleted == null)) {
                this.GetEmploymentInfoByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmploymentInfoByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetEmploymentInfoByUserID", new object[] {
                        piUserID}, this.GetEmploymentInfoByUserIDOperationCompleted, userState);
        }
        
        private void OnGetEmploymentInfoByUserIDOperationCompleted(object arg) {
            if ((this.GetEmploymentInfoByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmploymentInfoByUserIDCompleted(this, new GetEmploymentInfoByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmploymentInfoByUserIDAndValidDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmploymentInfo GetEmploymentInfoByUserIDAndValidDate(int piUserID, System.DateTime date) {
            object[] results = this.Invoke("GetEmploymentInfoByUserIDAndValidDate", new object[] {
                        piUserID,
                        date});
            return ((EmploymentInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmploymentInfoByUserIDAndValidDateAsync(int piUserID, System.DateTime date) {
            this.GetEmploymentInfoByUserIDAndValidDateAsync(piUserID, date, null);
        }
        
        /// <remarks/>
        public void GetEmploymentInfoByUserIDAndValidDateAsync(int piUserID, System.DateTime date, object userState) {
            if ((this.GetEmploymentInfoByUserIDAndValidDateOperationCompleted == null)) {
                this.GetEmploymentInfoByUserIDAndValidDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmploymentInfoByUserIDAndValidDateOperationCompleted);
            }
            this.InvokeAsync("GetEmploymentInfoByUserIDAndValidDate", new object[] {
                        piUserID,
                        date}, this.GetEmploymentInfoByUserIDAndValidDateOperationCompleted, userState);
        }
        
        private void OnGetEmploymentInfoByUserIDAndValidDateOperationCompleted(object arg) {
            if ((this.GetEmploymentInfoByUserIDAndValidDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmploymentInfoByUserIDAndValidDateCompleted(this, new GetEmploymentInfoByUserIDAndValidDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BasicStaffInfo {
        
        private int idField;
        
        private string staffNumberField;
        
        private string staffEngNameField;
        
        private string staffChiNameField;
        
        private string staffIDNumberField;
        
        private string companyNameField;
        
        private int personIDField;
        
        private int companyIDField;
        
        private int departmentIDField;
        
        private int positionIDField;
        
        private int securityGroupIDField;
        
        private int statusField;
        
        private int leaveClassField;
        
        private System.DateTime joinDateField;
        
        private System.DateTime quitDateField;
        
        private int mainBankIDField;
        
        private string mainBankACField;
        
        private int alternateBankIDField;
        
        private string alternateBankACField;
        
        private int paymentMethodField;
        
        private string securityGroupCodeField;
        
        private string employmentNumberField;
        
        private int employmentIDField;
        
        private int supervisorIDField;
        
        private System.DateTime dateOfBirthField;
        
        private int bonusSchemeIDField;
        
        private int contractIDField;
        
        private int contractGroupIDField;
        
        private string contractGroupCodeField;
        
        private string zoneCodeField;
        
        private string zoneDescriptionField;
        
        private string generalRemarksField;
        
        private int payrollTypeField;
        
        private int userIDField;
        
        private string userFullNameField;
        
        private int referralStaffIDField;
        
        private string companyCodeField;
        
        private System.DateTime companyJoinDateField;
        
        private string nickNameField;
        
        private System.Nullable<System.DateTime> contractStartDateField;
        
        private System.Nullable<System.DateTime> contractEndDateField;
        
        private int rankIDField;
        
        private string positionCodeField;
        
        private string positionDescriptionField;
        
        private string rankCodeField;
        
        private string rankDescriptionField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string StaffNumber {
            get {
                return this.staffNumberField;
            }
            set {
                this.staffNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StaffEngName {
            get {
                return this.staffEngNameField;
            }
            set {
                this.staffEngNameField = value;
            }
        }
        
        /// <remarks/>
        public string StaffChiName {
            get {
                return this.staffChiNameField;
            }
            set {
                this.staffChiNameField = value;
            }
        }
        
        /// <remarks/>
        public string StaffIDNumber {
            get {
                return this.staffIDNumberField;
            }
            set {
                this.staffIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public int PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int PositionID {
            get {
                return this.positionIDField;
            }
            set {
                this.positionIDField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityGroupID {
            get {
                return this.securityGroupIDField;
            }
            set {
                this.securityGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveClass {
            get {
                return this.leaveClassField;
            }
            set {
                this.leaveClassField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuitDate {
            get {
                return this.quitDateField;
            }
            set {
                this.quitDateField = value;
            }
        }
        
        /// <remarks/>
        public int MainBankID {
            get {
                return this.mainBankIDField;
            }
            set {
                this.mainBankIDField = value;
            }
        }
        
        /// <remarks/>
        public string MainBankAC {
            get {
                return this.mainBankACField;
            }
            set {
                this.mainBankACField = value;
            }
        }
        
        /// <remarks/>
        public int AlternateBankID {
            get {
                return this.alternateBankIDField;
            }
            set {
                this.alternateBankIDField = value;
            }
        }
        
        /// <remarks/>
        public string AlternateBankAC {
            get {
                return this.alternateBankACField;
            }
            set {
                this.alternateBankACField = value;
            }
        }
        
        /// <remarks/>
        public int PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroupCode {
            get {
                return this.securityGroupCodeField;
            }
            set {
                this.securityGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentNumber {
            get {
                return this.employmentNumberField;
            }
            set {
                this.employmentNumberField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int SupervisorID {
            get {
                return this.supervisorIDField;
            }
            set {
                this.supervisorIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public int BonusSchemeID {
            get {
                return this.bonusSchemeIDField;
            }
            set {
                this.bonusSchemeIDField = value;
            }
        }
        
        /// <remarks/>
        public int ContractID {
            get {
                return this.contractIDField;
            }
            set {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        public int ContractGroupID {
            get {
                return this.contractGroupIDField;
            }
            set {
                this.contractGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractGroupCode {
            get {
                return this.contractGroupCodeField;
            }
            set {
                this.contractGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneDescription {
            get {
                return this.zoneDescriptionField;
            }
            set {
                this.zoneDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string GeneralRemarks {
            get {
                return this.generalRemarksField;
            }
            set {
                this.generalRemarksField = value;
            }
        }
        
        /// <remarks/>
        public int PayrollType {
            get {
                return this.payrollTypeField;
            }
            set {
                this.payrollTypeField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public int ReferralStaffID {
            get {
                return this.referralStaffIDField;
            }
            set {
                this.referralStaffIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CompanyJoinDate {
            get {
                return this.companyJoinDateField;
            }
            set {
                this.companyJoinDateField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ContractStartDate {
            get {
                return this.contractStartDateField;
            }
            set {
                this.contractStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ContractEndDate {
            get {
                return this.contractEndDateField;
            }
            set {
                this.contractEndDateField = value;
            }
        }
        
        /// <remarks/>
        public int RankID {
            get {
                return this.rankIDField;
            }
            set {
                this.rankIDField = value;
            }
        }
        
        /// <remarks/>
        public string PositionCode {
            get {
                return this.positionCodeField;
            }
            set {
                this.positionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PositionDescription {
            get {
                return this.positionDescriptionField;
            }
            set {
                this.positionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RankCode {
            get {
                return this.rankCodeField;
            }
            set {
                this.rankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RankDescription {
            get {
                return this.rankDescriptionField;
            }
            set {
                this.rankDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrgUnitPosition {
        
        private int idField;
        
        private int orgUnitIDField;
        
        private int positionIDField;
        
        private int levelField;
        
        private int headCountField;
        
        private int sortSeqField;
        
        private int parentOrgUnitPositionIDField;
        
        private string positionDescField;
        
        private int noOfStaffField;
        
        private string parentOrgUnitPositionDescField;
        
        private int[] employmentIDsField;
        
        private string[] staffNamesField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int OrgUnitID {
            get {
                return this.orgUnitIDField;
            }
            set {
                this.orgUnitIDField = value;
            }
        }
        
        /// <remarks/>
        public int PositionID {
            get {
                return this.positionIDField;
            }
            set {
                this.positionIDField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public int HeadCount {
            get {
                return this.headCountField;
            }
            set {
                this.headCountField = value;
            }
        }
        
        /// <remarks/>
        public int SortSeq {
            get {
                return this.sortSeqField;
            }
            set {
                this.sortSeqField = value;
            }
        }
        
        /// <remarks/>
        public int ParentOrgUnitPositionID {
            get {
                return this.parentOrgUnitPositionIDField;
            }
            set {
                this.parentOrgUnitPositionIDField = value;
            }
        }
        
        /// <remarks/>
        public string PositionDesc {
            get {
                return this.positionDescField;
            }
            set {
                this.positionDescField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfStaff {
            get {
                return this.noOfStaffField;
            }
            set {
                this.noOfStaffField = value;
            }
        }
        
        /// <remarks/>
        public string ParentOrgUnitPositionDesc {
            get {
                return this.parentOrgUnitPositionDescField;
            }
            set {
                this.parentOrgUnitPositionDescField = value;
            }
        }
        
        /// <remarks/>
        public int[] EmploymentIDs {
            get {
                return this.employmentIDsField;
            }
            set {
                this.employmentIDsField = value;
            }
        }
        
        /// <remarks/>
        public string[] StaffNames {
            get {
                return this.staffNamesField;
            }
            set {
                this.staffNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employment_OrgUnit {
        
        private int idField;
        
        private int employmentIDField;
        
        private int orgUnitPositionIDField;
        
        private bool isMainOrgUnitField;
        
        private double programSourceAmountField;
        
        private double programSourcePercentField;
        
        private OrgUnitPosition oUPositionField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int OrgUnitPositionID {
            get {
                return this.orgUnitPositionIDField;
            }
            set {
                this.orgUnitPositionIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMainOrgUnit {
            get {
                return this.isMainOrgUnitField;
            }
            set {
                this.isMainOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        public double ProgramSourceAmount {
            get {
                return this.programSourceAmountField;
            }
            set {
                this.programSourceAmountField = value;
            }
        }
        
        /// <remarks/>
        public double ProgramSourcePercent {
            get {
                return this.programSourcePercentField;
            }
            set {
                this.programSourcePercentField = value;
            }
        }
        
        /// <remarks/>
        public OrgUnitPosition OUPosition {
            get {
                return this.oUPositionField;
            }
            set {
                this.oUPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmploymentInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BasicEmploymentInfo {
        
        private int contractIDField;
        
        private string zoneCodeField;
        
        private string zoneDescriptionField;
        
        private int positionIDField;
        
        private int areaIDField;
        
        private string stationCodeField;
        
        private string stationDescriptionField;
        
        private double wagesField;
        
        private bool isMainField;
        
        private bool isPartTimeField;
        
        private bool isCLField;
        
        private int statusField;
        
        private double oldWagesField;
        
        private int shiftIDField;
        
        private bool isHourlyBasisField;
        
        private string positionDescriptionField;
        
        private double wages28Field;
        
        private bool isContinuousEmploymentField;
        
        private byte[] staffPhotoField;
        
        private string photoPathField;
        
        /// <remarks/>
        public int ContractID {
            get {
                return this.contractIDField;
            }
            set {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneCode {
            get {
                return this.zoneCodeField;
            }
            set {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneDescription {
            get {
                return this.zoneDescriptionField;
            }
            set {
                this.zoneDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int PositionID {
            get {
                return this.positionIDField;
            }
            set {
                this.positionIDField = value;
            }
        }
        
        /// <remarks/>
        public int AreaID {
            get {
                return this.areaIDField;
            }
            set {
                this.areaIDField = value;
            }
        }
        
        /// <remarks/>
        public string StationCode {
            get {
                return this.stationCodeField;
            }
            set {
                this.stationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StationDescription {
            get {
                return this.stationDescriptionField;
            }
            set {
                this.stationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Wages {
            get {
                return this.wagesField;
            }
            set {
                this.wagesField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMain {
            get {
                return this.isMainField;
            }
            set {
                this.isMainField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPartTime {
            get {
                return this.isPartTimeField;
            }
            set {
                this.isPartTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCL {
            get {
                return this.isCLField;
            }
            set {
                this.isCLField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public double OldWages {
            get {
                return this.oldWagesField;
            }
            set {
                this.oldWagesField = value;
            }
        }
        
        /// <remarks/>
        public int ShiftID {
            get {
                return this.shiftIDField;
            }
            set {
                this.shiftIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHourlyBasis {
            get {
                return this.isHourlyBasisField;
            }
            set {
                this.isHourlyBasisField = value;
            }
        }
        
        /// <remarks/>
        public string PositionDescription {
            get {
                return this.positionDescriptionField;
            }
            set {
                this.positionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Wages28 {
            get {
                return this.wages28Field;
            }
            set {
                this.wages28Field = value;
            }
        }
        
        /// <remarks/>
        public bool IsContinuousEmployment {
            get {
                return this.isContinuousEmploymentField;
            }
            set {
                this.isContinuousEmploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] StaffPhoto {
            get {
                return this.staffPhotoField;
            }
            set {
                this.staffPhotoField = value;
            }
        }
        
        /// <remarks/>
        public string PhotoPath {
            get {
                return this.photoPathField;
            }
            set {
                this.photoPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmploymentInfo : BasicEmploymentInfo {
        
        private int idField;
        
        private string companyNameField;
        
        private int companyIDField;
        
        private string contractNameField;
        
        private string employmentNumberField;
        
        private int relatedEmploymentIDField;
        
        private string relatedEmploymentNumberField;
        
        private int staffIDField;
        
        private System.DateTime joinDateField;
        
        private System.DateTime quitDateField;
        
        private int leaveClassField;
        
        private string positionField;
        
        private string positionCodeField;
        
        private string staffNumberField;
        
        private string staffNameEField;
        
        private string staffNameCField;
        
        private string staffNameField;
        
        private string nickNameField;
        
        private string otherNameField;
        
        private string surnameField;
        
        private string contractCodeField;
        
        private string contractNumberField;
        
        private System.DateTime shiftTimeFromField;
        
        private System.DateTime shiftTimeToField;
        
        private string shiftCodeField;
        
        private int payrollTypeField;
        
        private int payMethodField;
        
        private int holidayTypeField;
        
        private System.DateTime commenceDateField;
        
        private System.DateTime terminationDateField;
        
        private string strCommenceDateField;
        
        private string strTerminationDateField;
        
        private bool isDailyBasisField;
        
        private bool isMonthEndCutOffField;
        
        private string alternativeBankAccountField;
        
        private System.DateTime employmentValidFromField;
        
        private System.DateTime employmentValidToField;
        
        private int securityGroupIDField;
        
        private bool staffStatusField;
        
        private System.DateTime modifiedDateField;
        
        private int terminateTypeField;
        
        private string terminateReasonField;
        
        private double noticeOfTerminateField;
        
        private double workingHourField;
        
        private string securityGroupCodeField;
        
        private string workingHourPatternField;
        
        private bool isNewContractField;
        
        private string remarksField;
        
        private int salaryTypeField;
        
        private int payScaleTypeField;
        
        private int payScalePointField;
        
        private decimal payScaleFractionField;
        
        private int personIDField;
        
        private string generateMonthField;
        
        private int generateSequenceField;
        
        private bool isLastStaffForSeqField;
        
        private int userIDField;
        
        private int employmentIDField;
        
        private double workingHourHalfDayField;
        
        private double workingHourAMField;
        
        private double workingHourPMField;
        
        private bool isCalculateUsing713Field;
        
        private int terminationNoticePeriodField;
        
        private int terminatedByField;
        
        private string contractGroupCodeField;
        
        private bool hasNoBenefitMPFField;
        
        private bool hasNoBenefitLeaveField;
        
        private int supervisorStaffIDField;
        
        private string empNumStaffNameField;
        
        private bool isCalcLeaveUseFirstCommenceDateField;
        
        private int approvalGroupIDField;
        
        private Employment_OrgUnit[] oUPositionsField;
        
        private string companyCodeField;
        
        private int firstEmploymentIDField;
        
        private string departmentDescField;
        
        private string firstEmploymentNumberField;
        
        private string rankCodeField;
        
        private bool isSelfEmployedField;
        
        private int rankIDField;
        
        private double hourlyWagesField;
        
        private bool isWagesDependOnShiftField;
        
        private int rankSortSeqField;
        
        private int positionSortSeqField;
        
        private string payScalePointStrField;
        
        private double monthlyWagesField;
        
        private string dailyWagesFormulaField;
        
        private int jobTypeField;
        
        private int leaveCutOffTypeField;
        
        private int salaryBasisIDField;
        
        private System.DateTime contractStartDateField;
        
        private System.DateTime contractEndDateField;
        
        private int employmentTransactionTypeField;
        
        private int contractPeriodByMonthField;
        
        private System.DateTime backPayEffectiveDateField;
        
        private double backPayWagesField;
        
        private System.DateTime probationDateField;
        
        private string rankDescriptionField;
        
        private string leaveClassDescriptionField;
        
        private System.DateTime renewalDateField;
        
        private bool isOverrideContractCriteriaField;
        
        private string shiftDescriptionField;
        
        private System.DateTime shiftBankOnTimeField;
        
        private System.DateTime shiftBankOffTimeField;
        
        private string iDNumberField;
        
        private string employmentTransactionTypeDescriptionField;
        
        private int contractTypeField;
        
        private string contractTypeDescriptionField;
        
        private int workingPatternTypeField;
        
        private int rosterCycleIDField;
        
        private int medicalPlanTypeIDField;
        
        private int medicalPlanOptField;
        
        private bool isGratuityEligibilityField;
        
        private int firstStaffIDField;
        
        private int needUpdatePreEmpoymentTerminateIDField;
        
        private int needUpdateNextEmpoymentCommenceIDField;
        
        private System.Nullable<int> oTExpiryDayValueField;
        
        private System.Nullable<int> oTExpiryDayUnitField;
        
        private bool isGratuityDeductEmployerMPFField;
        
        private System.Nullable<int> rosterGroupIDField;
        
        private string positionRemark1Field;
        
        private string positionRemark2Field;
        
        private string positionRemark3Field;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractName {
            get {
                return this.contractNameField;
            }
            set {
                this.contractNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentNumber {
            get {
                return this.employmentNumberField;
            }
            set {
                this.employmentNumberField = value;
            }
        }
        
        /// <remarks/>
        public int RelatedEmploymentID {
            get {
                return this.relatedEmploymentIDField;
            }
            set {
                this.relatedEmploymentIDField = value;
            }
        }
        
        /// <remarks/>
        public string RelatedEmploymentNumber {
            get {
                return this.relatedEmploymentNumberField;
            }
            set {
                this.relatedEmploymentNumberField = value;
            }
        }
        
        /// <remarks/>
        public int StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuitDate {
            get {
                return this.quitDateField;
            }
            set {
                this.quitDateField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveClass {
            get {
                return this.leaveClassField;
            }
            set {
                this.leaveClassField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string PositionCode {
            get {
                return this.positionCodeField;
            }
            set {
                this.positionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StaffNumber {
            get {
                return this.staffNumberField;
            }
            set {
                this.staffNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StaffNameE {
            get {
                return this.staffNameEField;
            }
            set {
                this.staffNameEField = value;
            }
        }
        
        /// <remarks/>
        public string StaffNameC {
            get {
                return this.staffNameCField;
            }
            set {
                this.staffNameCField = value;
            }
        }
        
        /// <remarks/>
        public string StaffName {
            get {
                return this.staffNameField;
            }
            set {
                this.staffNameField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string OtherName {
            get {
                return this.otherNameField;
            }
            set {
                this.otherNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string ContractCode {
            get {
                return this.contractCodeField;
            }
            set {
                this.contractCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShiftTimeFrom {
            get {
                return this.shiftTimeFromField;
            }
            set {
                this.shiftTimeFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShiftTimeTo {
            get {
                return this.shiftTimeToField;
            }
            set {
                this.shiftTimeToField = value;
            }
        }
        
        /// <remarks/>
        public string ShiftCode {
            get {
                return this.shiftCodeField;
            }
            set {
                this.shiftCodeField = value;
            }
        }
        
        /// <remarks/>
        public int PayrollType {
            get {
                return this.payrollTypeField;
            }
            set {
                this.payrollTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PayMethod {
            get {
                return this.payMethodField;
            }
            set {
                this.payMethodField = value;
            }
        }
        
        /// <remarks/>
        public int HolidayType {
            get {
                return this.holidayTypeField;
            }
            set {
                this.holidayTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CommenceDate {
            get {
                return this.commenceDateField;
            }
            set {
                this.commenceDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TerminationDate {
            get {
                return this.terminationDateField;
            }
            set {
                this.terminationDateField = value;
            }
        }
        
        /// <remarks/>
        public string strCommenceDate {
            get {
                return this.strCommenceDateField;
            }
            set {
                this.strCommenceDateField = value;
            }
        }
        
        /// <remarks/>
        public string strTerminationDate {
            get {
                return this.strTerminationDateField;
            }
            set {
                this.strTerminationDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDailyBasis {
            get {
                return this.isDailyBasisField;
            }
            set {
                this.isDailyBasisField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMonthEndCutOff {
            get {
                return this.isMonthEndCutOffField;
            }
            set {
                this.isMonthEndCutOffField = value;
            }
        }
        
        /// <remarks/>
        public string AlternativeBankAccount {
            get {
                return this.alternativeBankAccountField;
            }
            set {
                this.alternativeBankAccountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EmploymentValidFrom {
            get {
                return this.employmentValidFromField;
            }
            set {
                this.employmentValidFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EmploymentValidTo {
            get {
                return this.employmentValidToField;
            }
            set {
                this.employmentValidToField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityGroupID {
            get {
                return this.securityGroupIDField;
            }
            set {
                this.securityGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public bool StaffStatus {
            get {
                return this.staffStatusField;
            }
            set {
                this.staffStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        public int TerminateType {
            get {
                return this.terminateTypeField;
            }
            set {
                this.terminateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TerminateReason {
            get {
                return this.terminateReasonField;
            }
            set {
                this.terminateReasonField = value;
            }
        }
        
        /// <remarks/>
        public double NoticeOfTerminate {
            get {
                return this.noticeOfTerminateField;
            }
            set {
                this.noticeOfTerminateField = value;
            }
        }
        
        /// <remarks/>
        public double WorkingHour {
            get {
                return this.workingHourField;
            }
            set {
                this.workingHourField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroupCode {
            get {
                return this.securityGroupCodeField;
            }
            set {
                this.securityGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WorkingHourPattern {
            get {
                return this.workingHourPatternField;
            }
            set {
                this.workingHourPatternField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNewContract {
            get {
                return this.isNewContractField;
            }
            set {
                this.isNewContractField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public int SalaryType {
            get {
                return this.salaryTypeField;
            }
            set {
                this.salaryTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PayScaleType {
            get {
                return this.payScaleTypeField;
            }
            set {
                this.payScaleTypeField = value;
            }
        }
        
        /// <remarks/>
        public int PayScalePoint {
            get {
                return this.payScalePointField;
            }
            set {
                this.payScalePointField = value;
            }
        }
        
        /// <remarks/>
        public decimal PayScaleFraction {
            get {
                return this.payScaleFractionField;
            }
            set {
                this.payScaleFractionField = value;
            }
        }
        
        /// <remarks/>
        public int PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public string GenerateMonth {
            get {
                return this.generateMonthField;
            }
            set {
                this.generateMonthField = value;
            }
        }
        
        /// <remarks/>
        public int GenerateSequence {
            get {
                return this.generateSequenceField;
            }
            set {
                this.generateSequenceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLastStaffForSeq {
            get {
                return this.isLastStaffForSeqField;
            }
            set {
                this.isLastStaffForSeqField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public double WorkingHourHalfDay {
            get {
                return this.workingHourHalfDayField;
            }
            set {
                this.workingHourHalfDayField = value;
            }
        }
        
        /// <remarks/>
        public double WorkingHourAM {
            get {
                return this.workingHourAMField;
            }
            set {
                this.workingHourAMField = value;
            }
        }
        
        /// <remarks/>
        public double WorkingHourPM {
            get {
                return this.workingHourPMField;
            }
            set {
                this.workingHourPMField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCalculateUsing713 {
            get {
                return this.isCalculateUsing713Field;
            }
            set {
                this.isCalculateUsing713Field = value;
            }
        }
        
        /// <remarks/>
        public int TerminationNoticePeriod {
            get {
                return this.terminationNoticePeriodField;
            }
            set {
                this.terminationNoticePeriodField = value;
            }
        }
        
        /// <remarks/>
        public int TerminatedBy {
            get {
                return this.terminatedByField;
            }
            set {
                this.terminatedByField = value;
            }
        }
        
        /// <remarks/>
        public string ContractGroupCode {
            get {
                return this.contractGroupCodeField;
            }
            set {
                this.contractGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool HasNoBenefitMPF {
            get {
                return this.hasNoBenefitMPFField;
            }
            set {
                this.hasNoBenefitMPFField = value;
            }
        }
        
        /// <remarks/>
        public bool HasNoBenefitLeave {
            get {
                return this.hasNoBenefitLeaveField;
            }
            set {
                this.hasNoBenefitLeaveField = value;
            }
        }
        
        /// <remarks/>
        public int SupervisorStaffID {
            get {
                return this.supervisorStaffIDField;
            }
            set {
                this.supervisorStaffIDField = value;
            }
        }
        
        /// <remarks/>
        public string EmpNumStaffName {
            get {
                return this.empNumStaffNameField;
            }
            set {
                this.empNumStaffNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCalcLeaveUseFirstCommenceDate {
            get {
                return this.isCalcLeaveUseFirstCommenceDateField;
            }
            set {
                this.isCalcLeaveUseFirstCommenceDateField = value;
            }
        }
        
        /// <remarks/>
        public int ApprovalGroupID {
            get {
                return this.approvalGroupIDField;
            }
            set {
                this.approvalGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public Employment_OrgUnit[] OUPositions {
            get {
                return this.oUPositionsField;
            }
            set {
                this.oUPositionsField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public int FirstEmploymentID {
            get {
                return this.firstEmploymentIDField;
            }
            set {
                this.firstEmploymentIDField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentDesc {
            get {
                return this.departmentDescField;
            }
            set {
                this.departmentDescField = value;
            }
        }
        
        /// <remarks/>
        public string FirstEmploymentNumber {
            get {
                return this.firstEmploymentNumberField;
            }
            set {
                this.firstEmploymentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RankCode {
            get {
                return this.rankCodeField;
            }
            set {
                this.rankCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSelfEmployed {
            get {
                return this.isSelfEmployedField;
            }
            set {
                this.isSelfEmployedField = value;
            }
        }
        
        /// <remarks/>
        public int RankID {
            get {
                return this.rankIDField;
            }
            set {
                this.rankIDField = value;
            }
        }
        
        /// <remarks/>
        public double HourlyWages {
            get {
                return this.hourlyWagesField;
            }
            set {
                this.hourlyWagesField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWagesDependOnShift {
            get {
                return this.isWagesDependOnShiftField;
            }
            set {
                this.isWagesDependOnShiftField = value;
            }
        }
        
        /// <remarks/>
        public int RankSortSeq {
            get {
                return this.rankSortSeqField;
            }
            set {
                this.rankSortSeqField = value;
            }
        }
        
        /// <remarks/>
        public int PositionSortSeq {
            get {
                return this.positionSortSeqField;
            }
            set {
                this.positionSortSeqField = value;
            }
        }
        
        /// <remarks/>
        public string PayScalePointStr {
            get {
                return this.payScalePointStrField;
            }
            set {
                this.payScalePointStrField = value;
            }
        }
        
        /// <remarks/>
        public double MonthlyWages {
            get {
                return this.monthlyWagesField;
            }
            set {
                this.monthlyWagesField = value;
            }
        }
        
        /// <remarks/>
        public string DailyWagesFormula {
            get {
                return this.dailyWagesFormulaField;
            }
            set {
                this.dailyWagesFormulaField = value;
            }
        }
        
        /// <remarks/>
        public int JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveCutOffType {
            get {
                return this.leaveCutOffTypeField;
            }
            set {
                this.leaveCutOffTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SalaryBasisID {
            get {
                return this.salaryBasisIDField;
            }
            set {
                this.salaryBasisIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractStartDate {
            get {
                return this.contractStartDateField;
            }
            set {
                this.contractStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractEndDate {
            get {
                return this.contractEndDateField;
            }
            set {
                this.contractEndDateField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentTransactionType {
            get {
                return this.employmentTransactionTypeField;
            }
            set {
                this.employmentTransactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ContractPeriodByMonth {
            get {
                return this.contractPeriodByMonthField;
            }
            set {
                this.contractPeriodByMonthField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BackPayEffectiveDate {
            get {
                return this.backPayEffectiveDateField;
            }
            set {
                this.backPayEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public double BackPayWages {
            get {
                return this.backPayWagesField;
            }
            set {
                this.backPayWagesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProbationDate {
            get {
                return this.probationDateField;
            }
            set {
                this.probationDateField = value;
            }
        }
        
        /// <remarks/>
        public string RankDescription {
            get {
                return this.rankDescriptionField;
            }
            set {
                this.rankDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LeaveClassDescription {
            get {
                return this.leaveClassDescriptionField;
            }
            set {
                this.leaveClassDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RenewalDate {
            get {
                return this.renewalDateField;
            }
            set {
                this.renewalDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOverrideContractCriteria {
            get {
                return this.isOverrideContractCriteriaField;
            }
            set {
                this.isOverrideContractCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public string ShiftDescription {
            get {
                return this.shiftDescriptionField;
            }
            set {
                this.shiftDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShiftBankOnTime {
            get {
                return this.shiftBankOnTimeField;
            }
            set {
                this.shiftBankOnTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShiftBankOffTime {
            get {
                return this.shiftBankOffTimeField;
            }
            set {
                this.shiftBankOffTimeField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentTransactionTypeDescription {
            get {
                return this.employmentTransactionTypeDescriptionField;
            }
            set {
                this.employmentTransactionTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ContractType {
            get {
                return this.contractTypeField;
            }
            set {
                this.contractTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ContractTypeDescription {
            get {
                return this.contractTypeDescriptionField;
            }
            set {
                this.contractTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int WorkingPatternType {
            get {
                return this.workingPatternTypeField;
            }
            set {
                this.workingPatternTypeField = value;
            }
        }
        
        /// <remarks/>
        public int RosterCycleID {
            get {
                return this.rosterCycleIDField;
            }
            set {
                this.rosterCycleIDField = value;
            }
        }
        
        /// <remarks/>
        public int MedicalPlanTypeID {
            get {
                return this.medicalPlanTypeIDField;
            }
            set {
                this.medicalPlanTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int MedicalPlanOpt {
            get {
                return this.medicalPlanOptField;
            }
            set {
                this.medicalPlanOptField = value;
            }
        }
        
        /// <remarks/>
        public bool IsGratuityEligibility {
            get {
                return this.isGratuityEligibilityField;
            }
            set {
                this.isGratuityEligibilityField = value;
            }
        }
        
        /// <remarks/>
        public int FirstStaffID {
            get {
                return this.firstStaffIDField;
            }
            set {
                this.firstStaffIDField = value;
            }
        }
        
        /// <remarks/>
        public int NeedUpdatePreEmpoymentTerminateID {
            get {
                return this.needUpdatePreEmpoymentTerminateIDField;
            }
            set {
                this.needUpdatePreEmpoymentTerminateIDField = value;
            }
        }
        
        /// <remarks/>
        public int NeedUpdateNextEmpoymentCommenceID {
            get {
                return this.needUpdateNextEmpoymentCommenceIDField;
            }
            set {
                this.needUpdateNextEmpoymentCommenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OTExpiryDayValue {
            get {
                return this.oTExpiryDayValueField;
            }
            set {
                this.oTExpiryDayValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OTExpiryDayUnit {
            get {
                return this.oTExpiryDayUnitField;
            }
            set {
                this.oTExpiryDayUnitField = value;
            }
        }
        
        /// <remarks/>
        public bool IsGratuityDeductEmployerMPF {
            get {
                return this.isGratuityDeductEmployerMPFField;
            }
            set {
                this.isGratuityDeductEmployerMPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RosterGroupID {
            get {
                return this.rosterGroupIDField;
            }
            set {
                this.rosterGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public string PositionRemark1 {
            get {
                return this.positionRemark1Field;
            }
            set {
                this.positionRemark1Field = value;
            }
        }
        
        /// <remarks/>
        public string PositionRemark2 {
            get {
                return this.positionRemark2Field;
            }
            set {
                this.positionRemark2Field = value;
            }
        }
        
        /// <remarks/>
        public string PositionRemark3 {
            get {
                return this.positionRemark3Field;
            }
            set {
                this.positionRemark3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStaffIDByUserIDCompletedEventHandler(object sender, GetStaffIDByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStaffIDByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStaffIDByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BasicStaffInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BasicStaffInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetEmploymentInfoByUserIDCompletedEventHandler(object sender, GetEmploymentInfoByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmploymentInfoByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmploymentInfoByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmploymentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmploymentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetEmploymentInfoByUserIDAndValidDateCompletedEventHandler(object sender, GetEmploymentInfoByUserIDAndValidDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmploymentInfoByUserIDAndValidDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmploymentInfoByUserIDAndValidDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmploymentInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmploymentInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591