//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DAL.WebReference_codesetting {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CodeSettingsV2Soap", Namespace="http://tempuri.org/")]
    public partial class CodeSettingsV2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLeaveInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyWorkflowTaskByIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CodeSettingsV2() {
            this.Url = global::DAL.Properties.Settings.Default.DAL_WebReference_codesetting_CodeSettingsV2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLeaveInfoCompletedEventHandler GetLeaveInfoCompleted;
        
        /// <remarks/>
        public event GetMyWorkflowTaskByIDCompletedEventHandler GetMyWorkflowTaskByIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeaveInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LeaveInfo[] GetLeaveInfo() {
            object[] results = this.Invoke("GetLeaveInfo", new object[0]);
            return ((LeaveInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveInfoAsync() {
            this.GetLeaveInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetLeaveInfoAsync(object userState) {
            if ((this.GetLeaveInfoOperationCompleted == null)) {
                this.GetLeaveInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveInfoOperationCompleted);
            }
            this.InvokeAsync("GetLeaveInfo", new object[0], this.GetLeaveInfoOperationCompleted, userState);
        }
        
        private void OnGetLeaveInfoOperationCompleted(object arg) {
            if ((this.GetLeaveInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveInfoCompleted(this, new GetLeaveInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyWorkflowTaskByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MyWorkflowTask GetMyWorkflowTaskByID(int WorkflowTaskID) {
            object[] results = this.Invoke("GetMyWorkflowTaskByID", new object[] {
                        WorkflowTaskID});
            return ((MyWorkflowTask)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyWorkflowTaskByIDAsync(int WorkflowTaskID) {
            this.GetMyWorkflowTaskByIDAsync(WorkflowTaskID, null);
        }
        
        /// <remarks/>
        public void GetMyWorkflowTaskByIDAsync(int WorkflowTaskID, object userState) {
            if ((this.GetMyWorkflowTaskByIDOperationCompleted == null)) {
                this.GetMyWorkflowTaskByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyWorkflowTaskByIDOperationCompleted);
            }
            this.InvokeAsync("GetMyWorkflowTaskByID", new object[] {
                        WorkflowTaskID}, this.GetMyWorkflowTaskByIDOperationCompleted, userState);
        }
        
        private void OnGetMyWorkflowTaskByIDOperationCompleted(object arg) {
            if ((this.GetMyWorkflowTaskByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyWorkflowTaskByIDCompleted(this, new GetMyWorkflowTaskByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveInfo {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        private double payRatioField;
        
        private bool isAverageDailyRateField;
        
        private int statusField;
        
        private int portalStatusField;
        
        private bool isAccumulableLeaveField;
        
        private bool isEnforceAttachmentField;
        
        private bool isInclude713Field;
        
        private string accountCodeLeaveField;
        
        private int paySlipReportGroupField;
        
        private bool isAdjustInNextMonthField;
        
        private string leaveNotesField;
        
        private string entitleEffectiveDateField;
        
        private bool isIncludeGratuityField;
        
        private int accumulableLeaveTypeField;
        
        private int entitledByField;
        
        private int applyRequirementField;
        
        private decimal leaveExpiryAfterValueField;
        
        private decimal leaveAllowApplyBeforeValueField;
        
        private int leaveExpiryAfterUnitField;
        
        private int leaveAllowApplyBeforeUnitField;
        
        private bool isEnableAdvanceLeaveOnPortalField;
        
        private double launchConditionField;
        
        private double aLRoundUpOptionField;
        
        private string commonLeaveYearField;
        
        private bool isCompareEOLeaveField;
        
        private int carryForwardByField;
        
        private int grantEntitlementMethodField;
        
        private int entitleExpiryWaysField;
        
        private System.Nullable<int> entitleExpiryByAfterCarryForwardDateInMonthField;
        
        private System.Nullable<int> entitleExpiryByAfterCarryForwardDateInDayField;
        
        private string entitleExpiryBySpecificDateField;
        
        private int maxEntitlementFrequencyField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double PayRatio {
            get {
                return this.payRatioField;
            }
            set {
                this.payRatioField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAverageDailyRate {
            get {
                return this.isAverageDailyRateField;
            }
            set {
                this.isAverageDailyRateField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int PortalStatus {
            get {
                return this.portalStatusField;
            }
            set {
                this.portalStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAccumulableLeave {
            get {
                return this.isAccumulableLeaveField;
            }
            set {
                this.isAccumulableLeaveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnforceAttachment {
            get {
                return this.isEnforceAttachmentField;
            }
            set {
                this.isEnforceAttachmentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInclude713 {
            get {
                return this.isInclude713Field;
            }
            set {
                this.isInclude713Field = value;
            }
        }
        
        /// <remarks/>
        public string AccountCodeLeave {
            get {
                return this.accountCodeLeaveField;
            }
            set {
                this.accountCodeLeaveField = value;
            }
        }
        
        /// <remarks/>
        public int PaySlipReportGroup {
            get {
                return this.paySlipReportGroupField;
            }
            set {
                this.paySlipReportGroupField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAdjustInNextMonth {
            get {
                return this.isAdjustInNextMonthField;
            }
            set {
                this.isAdjustInNextMonthField = value;
            }
        }
        
        /// <remarks/>
        public string LeaveNotes {
            get {
                return this.leaveNotesField;
            }
            set {
                this.leaveNotesField = value;
            }
        }
        
        /// <remarks/>
        public string EntitleEffectiveDate {
            get {
                return this.entitleEffectiveDateField;
            }
            set {
                this.entitleEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsIncludeGratuity {
            get {
                return this.isIncludeGratuityField;
            }
            set {
                this.isIncludeGratuityField = value;
            }
        }
        
        /// <remarks/>
        public int AccumulableLeaveType {
            get {
                return this.accumulableLeaveTypeField;
            }
            set {
                this.accumulableLeaveTypeField = value;
            }
        }
        
        /// <remarks/>
        public int EntitledBy {
            get {
                return this.entitledByField;
            }
            set {
                this.entitledByField = value;
            }
        }
        
        /// <remarks/>
        public int ApplyRequirement {
            get {
                return this.applyRequirementField;
            }
            set {
                this.applyRequirementField = value;
            }
        }
        
        /// <remarks/>
        public decimal LeaveExpiryAfterValue {
            get {
                return this.leaveExpiryAfterValueField;
            }
            set {
                this.leaveExpiryAfterValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal LeaveAllowApplyBeforeValue {
            get {
                return this.leaveAllowApplyBeforeValueField;
            }
            set {
                this.leaveAllowApplyBeforeValueField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveExpiryAfterUnit {
            get {
                return this.leaveExpiryAfterUnitField;
            }
            set {
                this.leaveExpiryAfterUnitField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveAllowApplyBeforeUnit {
            get {
                return this.leaveAllowApplyBeforeUnitField;
            }
            set {
                this.leaveAllowApplyBeforeUnitField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnableAdvanceLeaveOnPortal {
            get {
                return this.isEnableAdvanceLeaveOnPortalField;
            }
            set {
                this.isEnableAdvanceLeaveOnPortalField = value;
            }
        }
        
        /// <remarks/>
        public double LaunchCondition {
            get {
                return this.launchConditionField;
            }
            set {
                this.launchConditionField = value;
            }
        }
        
        /// <remarks/>
        public double ALRoundUpOption {
            get {
                return this.aLRoundUpOptionField;
            }
            set {
                this.aLRoundUpOptionField = value;
            }
        }
        
        /// <remarks/>
        public string CommonLeaveYear {
            get {
                return this.commonLeaveYearField;
            }
            set {
                this.commonLeaveYearField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompareEOLeave {
            get {
                return this.isCompareEOLeaveField;
            }
            set {
                this.isCompareEOLeaveField = value;
            }
        }
        
        /// <remarks/>
        public int CarryForwardBy {
            get {
                return this.carryForwardByField;
            }
            set {
                this.carryForwardByField = value;
            }
        }
        
        /// <remarks/>
        public int GrantEntitlementMethod {
            get {
                return this.grantEntitlementMethodField;
            }
            set {
                this.grantEntitlementMethodField = value;
            }
        }
        
        /// <remarks/>
        public int EntitleExpiryWays {
            get {
                return this.entitleExpiryWaysField;
            }
            set {
                this.entitleExpiryWaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EntitleExpiryByAfterCarryForwardDateInMonth {
            get {
                return this.entitleExpiryByAfterCarryForwardDateInMonthField;
            }
            set {
                this.entitleExpiryByAfterCarryForwardDateInMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EntitleExpiryByAfterCarryForwardDateInDay {
            get {
                return this.entitleExpiryByAfterCarryForwardDateInDayField;
            }
            set {
                this.entitleExpiryByAfterCarryForwardDateInDayField = value;
            }
        }
        
        /// <remarks/>
        public string EntitleExpiryBySpecificDate {
            get {
                return this.entitleExpiryBySpecificDateField;
            }
            set {
                this.entitleExpiryBySpecificDateField = value;
            }
        }
        
        /// <remarks/>
        public int MaxEntitlementFrequency {
            get {
                return this.maxEntitlementFrequencyField;
            }
            set {
                this.maxEntitlementFrequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MyWorkflowTask {
        
        private int idField;
        
        private int userIDField;
        
        private int inOutTypeIDField;
        
        private int typeIDField;
        
        private int workflowInfoIDField;
        
        private int currentStepField;
        
        private string typeNameField;
        
        private string descriptionField;
        
        private string formulatedURLField;
        
        private int leaveRequestIDField;
        
        private System.DateTime modifiedDateField;
        
        private int modifiedUserField;
        
        private System.DateTime createDateField;
        
        private int createUserField;
        
        private bool isReadField;
        
        private string remarkField;
        
        private string fromUserNameField;
        
        private int statusField;
        
        private int employmentIDField;
        
        private string positionDescriptionField;
        
        private string toUserNameField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int InOutTypeID {
            get {
                return this.inOutTypeIDField;
            }
            set {
                this.inOutTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        public int WorkflowInfoID {
            get {
                return this.workflowInfoIDField;
            }
            set {
                this.workflowInfoIDField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentStep {
            get {
                return this.currentStepField;
            }
            set {
                this.currentStepField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FormulatedURL {
            get {
                return this.formulatedURLField;
            }
            set {
                this.formulatedURLField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveRequestID {
            get {
                return this.leaveRequestIDField;
            }
            set {
                this.leaveRequestIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        public int ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRead {
            get {
                return this.isReadField;
            }
            set {
                this.isReadField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string FromUserName {
            get {
                return this.fromUserNameField;
            }
            set {
                this.fromUserNameField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string PositionDescription {
            get {
                return this.positionDescriptionField;
            }
            set {
                this.positionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ToUserName {
            get {
                return this.toUserNameField;
            }
            set {
                this.toUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetLeaveInfoCompletedEventHandler(object sender, GetLeaveInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LeaveInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeaveInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMyWorkflowTaskByIDCompletedEventHandler(object sender, GetMyWorkflowTaskByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyWorkflowTaskByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyWorkflowTaskByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MyWorkflowTask Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MyWorkflowTask)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591