//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WebServiceLayer.WebReference_leave {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LeaveManagementV2Soap", Namespace="http://tempuri.org/")]
    public partial class LeaveManagementV2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllLeaveTypeByStaffIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOnlineLeaveApplicationRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllLeaveMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaveMasterByEmploymentIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaveMasterByPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaveMasterByRIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaveDetailsByReuestIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LeaveManagementV2() {
            this.Url = global::WebServiceLayer.Properties.Settings.Default.WebServiceLayer_WebReference_leave_LeaveManagementV2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllLeaveTypeByStaffIDCompletedEventHandler GetAllLeaveTypeByStaffIDCompleted;
        
        /// <remarks/>
        public event InsertOnlineLeaveApplicationRequestCompletedEventHandler InsertOnlineLeaveApplicationRequestCompleted;
        
        /// <remarks/>
        public event GetAllLeaveMasterCompletedEventHandler GetAllLeaveMasterCompleted;
        
        /// <remarks/>
        public event GetLeaveMasterByEmploymentIDCompletedEventHandler GetLeaveMasterByEmploymentIDCompleted;
        
        /// <remarks/>
        public event GetLeaveMasterByPIDCompletedEventHandler GetLeaveMasterByPIDCompleted;
        
        /// <remarks/>
        public event GetLeaveMasterByRIDCompletedEventHandler GetLeaveMasterByRIDCompleted;
        
        /// <remarks/>
        public event GetLeaveDetailsByReuestIDCompletedEventHandler GetLeaveDetailsByReuestIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllLeaveTypeByStaffID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public t_Leave[] GetAllLeaveTypeByStaffID(int staffid) {
            object[] results = this.Invoke("GetAllLeaveTypeByStaffID", new object[] {
                        staffid});
            return ((t_Leave[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllLeaveTypeByStaffIDAsync(int staffid) {
            this.GetAllLeaveTypeByStaffIDAsync(staffid, null);
        }
        
        /// <remarks/>
        public void GetAllLeaveTypeByStaffIDAsync(int staffid, object userState) {
            if ((this.GetAllLeaveTypeByStaffIDOperationCompleted == null)) {
                this.GetAllLeaveTypeByStaffIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllLeaveTypeByStaffIDOperationCompleted);
            }
            this.InvokeAsync("GetAllLeaveTypeByStaffID", new object[] {
                        staffid}, this.GetAllLeaveTypeByStaffIDOperationCompleted, userState);
        }
        
        private void OnGetAllLeaveTypeByStaffIDOperationCompleted(object arg) {
            if ((this.GetAllLeaveTypeByStaffIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllLeaveTypeByStaffIDCompleted(this, new GetAllLeaveTypeByStaffIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertOnlineLeaveApplicationRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorMessageInfo InsertOnlineLeaveApplicationRequest(StaffLeaveRequest[] poStaffLeaveRequest, ApprovalRequestStatus p_enumStatus, int piUserID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> piWorkflowDelegationToStaffID) {
            object[] results = this.Invoke("InsertOnlineLeaveApplicationRequest", new object[] {
                        poStaffLeaveRequest,
                        p_enumStatus,
                        piUserID,
                        piWorkflowDelegationToStaffID});
            return ((ErrorMessageInfo)(results[0]));
        }
        
        /// <remarks/>
        public void InsertOnlineLeaveApplicationRequestAsync(StaffLeaveRequest[] poStaffLeaveRequest, ApprovalRequestStatus p_enumStatus, int piUserID, System.Nullable<int> piWorkflowDelegationToStaffID) {
            this.InsertOnlineLeaveApplicationRequestAsync(poStaffLeaveRequest, p_enumStatus, piUserID, piWorkflowDelegationToStaffID, null);
        }
        
        /// <remarks/>
        public void InsertOnlineLeaveApplicationRequestAsync(StaffLeaveRequest[] poStaffLeaveRequest, ApprovalRequestStatus p_enumStatus, int piUserID, System.Nullable<int> piWorkflowDelegationToStaffID, object userState) {
            if ((this.InsertOnlineLeaveApplicationRequestOperationCompleted == null)) {
                this.InsertOnlineLeaveApplicationRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOnlineLeaveApplicationRequestOperationCompleted);
            }
            this.InvokeAsync("InsertOnlineLeaveApplicationRequest", new object[] {
                        poStaffLeaveRequest,
                        p_enumStatus,
                        piUserID,
                        piWorkflowDelegationToStaffID}, this.InsertOnlineLeaveApplicationRequestOperationCompleted, userState);
        }
        
        private void OnInsertOnlineLeaveApplicationRequestOperationCompleted(object arg) {
            if ((this.InsertOnlineLeaveApplicationRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertOnlineLeaveApplicationRequestCompleted(this, new InsertOnlineLeaveApplicationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllLeaveMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LeaveRequestMaster[] GetAllLeaveMaster() {
            object[] results = this.Invoke("GetAllLeaveMaster", new object[0]);
            return ((LeaveRequestMaster[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllLeaveMasterAsync() {
            this.GetAllLeaveMasterAsync(null);
        }
        
        /// <remarks/>
        public void GetAllLeaveMasterAsync(object userState) {
            if ((this.GetAllLeaveMasterOperationCompleted == null)) {
                this.GetAllLeaveMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllLeaveMasterOperationCompleted);
            }
            this.InvokeAsync("GetAllLeaveMaster", new object[0], this.GetAllLeaveMasterOperationCompleted, userState);
        }
        
        private void OnGetAllLeaveMasterOperationCompleted(object arg) {
            if ((this.GetAllLeaveMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllLeaveMasterCompleted(this, new GetAllLeaveMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeaveMasterByEmploymentID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LeaveRequestMaster[] GetLeaveMasterByEmploymentID(int employmentID) {
            object[] results = this.Invoke("GetLeaveMasterByEmploymentID", new object[] {
                        employmentID});
            return ((LeaveRequestMaster[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveMasterByEmploymentIDAsync(int employmentID) {
            this.GetLeaveMasterByEmploymentIDAsync(employmentID, null);
        }
        
        /// <remarks/>
        public void GetLeaveMasterByEmploymentIDAsync(int employmentID, object userState) {
            if ((this.GetLeaveMasterByEmploymentIDOperationCompleted == null)) {
                this.GetLeaveMasterByEmploymentIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveMasterByEmploymentIDOperationCompleted);
            }
            this.InvokeAsync("GetLeaveMasterByEmploymentID", new object[] {
                        employmentID}, this.GetLeaveMasterByEmploymentIDOperationCompleted, userState);
        }
        
        private void OnGetLeaveMasterByEmploymentIDOperationCompleted(object arg) {
            if ((this.GetLeaveMasterByEmploymentIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveMasterByEmploymentIDCompleted(this, new GetLeaveMasterByEmploymentIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeaveMasterByPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LeaveRequestMaster[] GetLeaveMasterByPID(int PID) {
            object[] results = this.Invoke("GetLeaveMasterByPID", new object[] {
                        PID});
            return ((LeaveRequestMaster[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveMasterByPIDAsync(int PID) {
            this.GetLeaveMasterByPIDAsync(PID, null);
        }
        
        /// <remarks/>
        public void GetLeaveMasterByPIDAsync(int PID, object userState) {
            if ((this.GetLeaveMasterByPIDOperationCompleted == null)) {
                this.GetLeaveMasterByPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveMasterByPIDOperationCompleted);
            }
            this.InvokeAsync("GetLeaveMasterByPID", new object[] {
                        PID}, this.GetLeaveMasterByPIDOperationCompleted, userState);
        }
        
        private void OnGetLeaveMasterByPIDOperationCompleted(object arg) {
            if ((this.GetLeaveMasterByPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveMasterByPIDCompleted(this, new GetLeaveMasterByPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeaveMasterByRID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LeaveRequestMaster GetLeaveMasterByRID(int RID) {
            object[] results = this.Invoke("GetLeaveMasterByRID", new object[] {
                        RID});
            return ((LeaveRequestMaster)(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveMasterByRIDAsync(int RID) {
            this.GetLeaveMasterByRIDAsync(RID, null);
        }
        
        /// <remarks/>
        public void GetLeaveMasterByRIDAsync(int RID, object userState) {
            if ((this.GetLeaveMasterByRIDOperationCompleted == null)) {
                this.GetLeaveMasterByRIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveMasterByRIDOperationCompleted);
            }
            this.InvokeAsync("GetLeaveMasterByRID", new object[] {
                        RID}, this.GetLeaveMasterByRIDOperationCompleted, userState);
        }
        
        private void OnGetLeaveMasterByRIDOperationCompleted(object arg) {
            if ((this.GetLeaveMasterByRIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveMasterByRIDCompleted(this, new GetLeaveMasterByRIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeaveDetailsByReuestID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public t_StaffLeaveRequestDetail[] GetLeaveDetailsByReuestID(int requestid) {
            object[] results = this.Invoke("GetLeaveDetailsByReuestID", new object[] {
                        requestid});
            return ((t_StaffLeaveRequestDetail[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveDetailsByReuestIDAsync(int requestid) {
            this.GetLeaveDetailsByReuestIDAsync(requestid, null);
        }
        
        /// <remarks/>
        public void GetLeaveDetailsByReuestIDAsync(int requestid, object userState) {
            if ((this.GetLeaveDetailsByReuestIDOperationCompleted == null)) {
                this.GetLeaveDetailsByReuestIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveDetailsByReuestIDOperationCompleted);
            }
            this.InvokeAsync("GetLeaveDetailsByReuestID", new object[] {
                        requestid}, this.GetLeaveDetailsByReuestIDOperationCompleted, userState);
        }
        
        private void OnGetLeaveDetailsByReuestIDOperationCompleted(object arg) {
            if ((this.GetLeaveDetailsByReuestIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveDetailsByReuestIDCompleted(this, new GetLeaveDetailsByReuestIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_Leave {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        private double payRatioField;
        
        private bool isAverageDailyRateField;
        
        private byte statusField;
        
        private System.DateTime modifiedDateField;
        
        private int modifiedUserField;
        
        private System.DateTime createDateField;
        
        private int createUserField;
        
        private byte portalStatusField;
        
        private bool isAccumulableLeaveField;
        
        private bool isEnforceAttachmentField;
        
        private bool isInclude713Field;
        
        private bool isAdjustInNextMonthField;
        
        private string accountCodeLeaveField;
        
        private int paySlipReportGroupIDField;
        
        private string leaveNotesField;
        
        private string entitleEffectiveDateField;
        
        private bool isIncludeGratuityField;
        
        private short accumulableLeaveTypeField;
        
        private bool isEnableAdvanceLeaveOnPortalField;
        
        private int applyRequirementField;
        
        private int entitledByField;
        
        private decimal leaveAllowApplyBeforeValueField;
        
        private int leaveAllowApplyBeforeUnitField;
        
        private decimal leaveExpiryAfterValueField;
        
        private int leaveExpiryAfterUnitField;
        
        private string commonLeaveYearField;
        
        private System.Nullable<bool> isCompareEOLeaveField;
        
        private System.Nullable<int> carryForwardByField;
        
        private int grantEntitlementMethodField;
        
        private int entitleExpiryWaysField;
        
        private System.Nullable<int> entitleExpiryByAfterCarryForwardDateInMonthField;
        
        private System.Nullable<int> entitleExpiryByAfterCarryForwardDateInDayField;
        
        private string entitleExpiryBySpecificDateField;
        
        private int maxEntitlementFrequencyField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double PayRatio {
            get {
                return this.payRatioField;
            }
            set {
                this.payRatioField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAverageDailyRate {
            get {
                return this.isAverageDailyRateField;
            }
            set {
                this.isAverageDailyRateField = value;
            }
        }
        
        /// <remarks/>
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        public int ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public byte PortalStatus {
            get {
                return this.portalStatusField;
            }
            set {
                this.portalStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAccumulableLeave {
            get {
                return this.isAccumulableLeaveField;
            }
            set {
                this.isAccumulableLeaveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnforceAttachment {
            get {
                return this.isEnforceAttachmentField;
            }
            set {
                this.isEnforceAttachmentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInclude713 {
            get {
                return this.isInclude713Field;
            }
            set {
                this.isInclude713Field = value;
            }
        }
        
        /// <remarks/>
        public bool IsAdjustInNextMonth {
            get {
                return this.isAdjustInNextMonthField;
            }
            set {
                this.isAdjustInNextMonthField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCodeLeave {
            get {
                return this.accountCodeLeaveField;
            }
            set {
                this.accountCodeLeaveField = value;
            }
        }
        
        /// <remarks/>
        public int PaySlipReportGroupID {
            get {
                return this.paySlipReportGroupIDField;
            }
            set {
                this.paySlipReportGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public string LeaveNotes {
            get {
                return this.leaveNotesField;
            }
            set {
                this.leaveNotesField = value;
            }
        }
        
        /// <remarks/>
        public string EntitleEffectiveDate {
            get {
                return this.entitleEffectiveDateField;
            }
            set {
                this.entitleEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsIncludeGratuity {
            get {
                return this.isIncludeGratuityField;
            }
            set {
                this.isIncludeGratuityField = value;
            }
        }
        
        /// <remarks/>
        public short AccumulableLeaveType {
            get {
                return this.accumulableLeaveTypeField;
            }
            set {
                this.accumulableLeaveTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnableAdvanceLeaveOnPortal {
            get {
                return this.isEnableAdvanceLeaveOnPortalField;
            }
            set {
                this.isEnableAdvanceLeaveOnPortalField = value;
            }
        }
        
        /// <remarks/>
        public int ApplyRequirement {
            get {
                return this.applyRequirementField;
            }
            set {
                this.applyRequirementField = value;
            }
        }
        
        /// <remarks/>
        public int EntitledBy {
            get {
                return this.entitledByField;
            }
            set {
                this.entitledByField = value;
            }
        }
        
        /// <remarks/>
        public decimal LeaveAllowApplyBeforeValue {
            get {
                return this.leaveAllowApplyBeforeValueField;
            }
            set {
                this.leaveAllowApplyBeforeValueField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveAllowApplyBeforeUnit {
            get {
                return this.leaveAllowApplyBeforeUnitField;
            }
            set {
                this.leaveAllowApplyBeforeUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal LeaveExpiryAfterValue {
            get {
                return this.leaveExpiryAfterValueField;
            }
            set {
                this.leaveExpiryAfterValueField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveExpiryAfterUnit {
            get {
                return this.leaveExpiryAfterUnitField;
            }
            set {
                this.leaveExpiryAfterUnitField = value;
            }
        }
        
        /// <remarks/>
        public string CommonLeaveYear {
            get {
                return this.commonLeaveYearField;
            }
            set {
                this.commonLeaveYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsCompareEOLeave {
            get {
                return this.isCompareEOLeaveField;
            }
            set {
                this.isCompareEOLeaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CarryForwardBy {
            get {
                return this.carryForwardByField;
            }
            set {
                this.carryForwardByField = value;
            }
        }
        
        /// <remarks/>
        public int GrantEntitlementMethod {
            get {
                return this.grantEntitlementMethodField;
            }
            set {
                this.grantEntitlementMethodField = value;
            }
        }
        
        /// <remarks/>
        public int EntitleExpiryWays {
            get {
                return this.entitleExpiryWaysField;
            }
            set {
                this.entitleExpiryWaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EntitleExpiryByAfterCarryForwardDateInMonth {
            get {
                return this.entitleExpiryByAfterCarryForwardDateInMonthField;
            }
            set {
                this.entitleExpiryByAfterCarryForwardDateInMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EntitleExpiryByAfterCarryForwardDateInDay {
            get {
                return this.entitleExpiryByAfterCarryForwardDateInDayField;
            }
            set {
                this.entitleExpiryByAfterCarryForwardDateInDayField = value;
            }
        }
        
        /// <remarks/>
        public string EntitleExpiryBySpecificDate {
            get {
                return this.entitleExpiryBySpecificDateField;
            }
            set {
                this.entitleExpiryBySpecificDateField = value;
            }
        }
        
        /// <remarks/>
        public int MaxEntitlementFrequency {
            get {
                return this.maxEntitlementFrequencyField;
            }
            set {
                this.maxEntitlementFrequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_StaffLeaveRequestDetail {
        
        private int requestIDField;
        
        private int employmentIDField;
        
        private int leaveIDField;
        
        private System.DateTime dateField;
        
        private bool isHalfDayField;
        
        private double unitField;
        
        private string remarksField;
        
        private System.DateTime createDateField;
        
        private int createUserField;
        
        private System.DateTime modifiedDateField;
        
        private int modifiedUserField;
        
        private int payrollPeriodIDField;
        
        private int sectionField;
        
        private int leaveCalculationTypeIDField;
        
        private byte statusField;
        
        private System.Nullable<System.DateTime> leaveFromField;
        
        private System.Nullable<System.DateTime> leaveToField;
        
        private System.Nullable<double> leaveHoursField;
        
        private System.Nullable<double> sectionsField;
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveID {
            get {
                return this.leaveIDField;
            }
            set {
                this.leaveIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHalfDay {
            get {
                return this.isHalfDayField;
            }
            set {
                this.isHalfDayField = value;
            }
        }
        
        /// <remarks/>
        public double Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        public int ModifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
            }
        }
        
        /// <remarks/>
        public int PayrollPeriodID {
            get {
                return this.payrollPeriodIDField;
            }
            set {
                this.payrollPeriodIDField = value;
            }
        }
        
        /// <remarks/>
        public int Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveCalculationTypeID {
            get {
                return this.leaveCalculationTypeIDField;
            }
            set {
                this.leaveCalculationTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LeaveFrom {
            get {
                return this.leaveFromField;
            }
            set {
                this.leaveFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LeaveTo {
            get {
                return this.leaveToField;
            }
            set {
                this.leaveToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LeaveHours {
            get {
                return this.leaveHoursField;
            }
            set {
                this.leaveHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveRequestMaster {
        
        private int requestIDField;
        
        private int employmentIDField;
        
        private int minLeaveIDField;
        
        private int maxLeaveIDField;
        
        private System.DateTime createDateField;
        
        private System.DateTime leavefromField;
        
        private System.DateTime leavetoField;
        
        private double totaldaysField;
        
        private System.Nullable<int> delegationToStaffIDField;
        
        private string inputSourceField;
        
        private byte statusField;
        
        private string remarksField;
        
        private string extendField;
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int employmentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int MinLeaveID {
            get {
                return this.minLeaveIDField;
            }
            set {
                this.minLeaveIDField = value;
            }
        }
        
        /// <remarks/>
        public int MaxLeaveID {
            get {
                return this.maxLeaveIDField;
            }
            set {
                this.maxLeaveIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime leavefrom {
            get {
                return this.leavefromField;
            }
            set {
                this.leavefromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime leaveto {
            get {
                return this.leavetoField;
            }
            set {
                this.leavetoField = value;
            }
        }
        
        /// <remarks/>
        public double totaldays {
            get {
                return this.totaldaysField;
            }
            set {
                this.totaldaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DelegationToStaffID {
            get {
                return this.delegationToStaffIDField;
            }
            set {
                this.delegationToStaffIDField = value;
            }
        }
        
        /// <remarks/>
        public string inputSource {
            get {
                return this.inputSourceField;
            }
            set {
                this.inputSourceField = value;
            }
        }
        
        /// <remarks/>
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string extend {
            get {
                return this.extendField;
            }
            set {
                this.extendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorMessageItem {
        
        private bool isMessageListField;
        
        private string messageField;
        
        private string messageParameter1Field;
        
        private string messageParameter2Field;
        
        private string messageParameter3Field;
        
        private ErrorMessageSeverity severityField;
        
        /// <remarks/>
        public bool IsMessageList {
            get {
                return this.isMessageListField;
            }
            set {
                this.isMessageListField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string MessageParameter1 {
            get {
                return this.messageParameter1Field;
            }
            set {
                this.messageParameter1Field = value;
            }
        }
        
        /// <remarks/>
        public string MessageParameter2 {
            get {
                return this.messageParameter2Field;
            }
            set {
                this.messageParameter2Field = value;
            }
        }
        
        /// <remarks/>
        public string MessageParameter3 {
            get {
                return this.messageParameter3Field;
            }
            set {
                this.messageParameter3Field = value;
            }
        }
        
        /// <remarks/>
        public ErrorMessageSeverity Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ErrorMessageSeverity {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        INFORMATION,
        
        /// <remarks/>
        VALIDATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorMessageInfo {
        
        private int processIDField;
        
        private int[] processIDListField;
        
        private int affectedRecordCountField;
        
        private string errorMessageField;
        
        private string completedRatioField;
        
        private bool isMessageListField;
        
        private ErrorMessageItem[] errorMessageListField;
        
        /// <remarks/>
        public int ProcessID {
            get {
                return this.processIDField;
            }
            set {
                this.processIDField = value;
            }
        }
        
        /// <remarks/>
        public int[] ProcessIDList {
            get {
                return this.processIDListField;
            }
            set {
                this.processIDListField = value;
            }
        }
        
        /// <remarks/>
        public int AffectedRecordCount {
            get {
                return this.affectedRecordCountField;
            }
            set {
                this.affectedRecordCountField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string CompletedRatio {
            get {
                return this.completedRatioField;
            }
            set {
                this.completedRatioField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMessageList {
            get {
                return this.isMessageListField;
            }
            set {
                this.isMessageListField = value;
            }
        }
        
        /// <remarks/>
        public ErrorMessageItem[] ErrorMessageList {
            get {
                return this.errorMessageListField;
            }
            set {
                this.errorMessageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StaffLeaveRequest {
        
        private int idField;
        
        private int statusField;
        
        private int employmentIDField;
        
        private int leaveIDField;
        
        private string leaveTypeNameField;
        
        private System.DateTime leaveDateField;
        
        private bool isHalfDayField;
        
        private double unitField;
        
        private string remarksField;
        
        private string deleteKeyField;
        
        private string descriptionField;
        
        private System.DateTime createDateField;
        
        private int sectionField;
        
        private string employmentNumberField;
        
        private string compareKeyField;
        
        private string nameField;
        
        private string nameCHField;
        
        private string holidayCodeField;
        
        private int leaveCalculationTypeIDField;
        
        private string leaveCalculationTypeDescField;
        
        private int firstEmploymentIDField;
        
        private string firstEmploymentNumberField;
        
        private bool isApprovedField;
        
        private int requestIDField;
        
        private System.Nullable<int> delegationToStaffIDField;
        
        private double leaveHoursField;
        
        private double totalWorkHoursField;
        
        private double sectionsField;
        
        private System.DateTime leaveHoursFromField;
        
        private System.DateTime leaveHoursToField;
        
        private int displaySectionField;
        
        private string displayUnitField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int EmploymentID {
            get {
                return this.employmentIDField;
            }
            set {
                this.employmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveID {
            get {
                return this.leaveIDField;
            }
            set {
                this.leaveIDField = value;
            }
        }
        
        /// <remarks/>
        public string LeaveTypeName {
            get {
                return this.leaveTypeNameField;
            }
            set {
                this.leaveTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LeaveDate {
            get {
                return this.leaveDateField;
            }
            set {
                this.leaveDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHalfDay {
            get {
                return this.isHalfDayField;
            }
            set {
                this.isHalfDayField = value;
            }
        }
        
        /// <remarks/>
        public double Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string DeleteKey {
            get {
                return this.deleteKeyField;
            }
            set {
                this.deleteKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentNumber {
            get {
                return this.employmentNumberField;
            }
            set {
                this.employmentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CompareKey {
            get {
                return this.compareKeyField;
            }
            set {
                this.compareKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string NameCH {
            get {
                return this.nameCHField;
            }
            set {
                this.nameCHField = value;
            }
        }
        
        /// <remarks/>
        public string HolidayCode {
            get {
                return this.holidayCodeField;
            }
            set {
                this.holidayCodeField = value;
            }
        }
        
        /// <remarks/>
        public int LeaveCalculationTypeID {
            get {
                return this.leaveCalculationTypeIDField;
            }
            set {
                this.leaveCalculationTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LeaveCalculationTypeDesc {
            get {
                return this.leaveCalculationTypeDescField;
            }
            set {
                this.leaveCalculationTypeDescField = value;
            }
        }
        
        /// <remarks/>
        public int FirstEmploymentID {
            get {
                return this.firstEmploymentIDField;
            }
            set {
                this.firstEmploymentIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstEmploymentNumber {
            get {
                return this.firstEmploymentNumberField;
            }
            set {
                this.firstEmploymentNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsApproved {
            get {
                return this.isApprovedField;
            }
            set {
                this.isApprovedField = value;
            }
        }
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DelegationToStaffID {
            get {
                return this.delegationToStaffIDField;
            }
            set {
                this.delegationToStaffIDField = value;
            }
        }
        
        /// <remarks/>
        public double LeaveHours {
            get {
                return this.leaveHoursField;
            }
            set {
                this.leaveHoursField = value;
            }
        }
        
        /// <remarks/>
        public double TotalWorkHours {
            get {
                return this.totalWorkHoursField;
            }
            set {
                this.totalWorkHoursField = value;
            }
        }
        
        /// <remarks/>
        public double Sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LeaveHoursFrom {
            get {
                return this.leaveHoursFromField;
            }
            set {
                this.leaveHoursFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LeaveHoursTo {
            get {
                return this.leaveHoursToField;
            }
            set {
                this.leaveHoursToField = value;
            }
        }
        
        /// <remarks/>
        public int DisplaySection {
            get {
                return this.displaySectionField;
            }
            set {
                this.displaySectionField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayUnit {
            get {
                return this.displayUnitField;
            }
            set {
                this.displayUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApprovalRequestStatus {
        
        /// <remarks/>
        SENDEMAIL,
        
        /// <remarks/>
        NEW,
        
        /// <remarks/>
        WAIT_FOR_APPROVE,
        
        /// <remarks/>
        APPROVE,
        
        /// <remarks/>
        REJECT,
        
        /// <remarks/>
        CANCEL,
        
        /// <remarks/>
        WAIT_FOR_CANCEL,
        
        /// <remarks/>
        CONFIRM_CANCEL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllLeaveTypeByStaffIDCompletedEventHandler(object sender, GetAllLeaveTypeByStaffIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllLeaveTypeByStaffIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllLeaveTypeByStaffIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public t_Leave[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((t_Leave[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertOnlineLeaveApplicationRequestCompletedEventHandler(object sender, InsertOnlineLeaveApplicationRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertOnlineLeaveApplicationRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertOnlineLeaveApplicationRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorMessageInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorMessageInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllLeaveMasterCompletedEventHandler(object sender, GetAllLeaveMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllLeaveMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllLeaveMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LeaveRequestMaster[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeaveRequestMaster[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetLeaveMasterByEmploymentIDCompletedEventHandler(object sender, GetLeaveMasterByEmploymentIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveMasterByEmploymentIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveMasterByEmploymentIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LeaveRequestMaster[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeaveRequestMaster[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetLeaveMasterByPIDCompletedEventHandler(object sender, GetLeaveMasterByPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveMasterByPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveMasterByPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LeaveRequestMaster[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeaveRequestMaster[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetLeaveMasterByRIDCompletedEventHandler(object sender, GetLeaveMasterByRIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveMasterByRIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveMasterByRIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LeaveRequestMaster Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LeaveRequestMaster)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetLeaveDetailsByReuestIDCompletedEventHandler(object sender, GetLeaveDetailsByReuestIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveDetailsByReuestIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveDetailsByReuestIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public t_StaffLeaveRequestDetail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((t_StaffLeaveRequestDetail[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591